#!/usr/bin/env node
/*
 * Convert snarkjs Groth16 verification_key.json files into the `Groth16Verifyingkey` byte layout
 * expected by groth16-solana (Light Protocol). Writes programs/sieve/src/verifying_key.rs.
 *
 * Usage: node parse_vk_to_rust.js <withdraw_vk.json> <ragequit_vk.json> <out.rs>
 *
 * Notes / footguns:
 *  - Field elements are emitted big-endian, 32 bytes. G1 = x||y (64B). G2 = x_c1||x_c0||y_c1||y_c0
 *    (128B) — the c1/c0 SWAP matches ark-bn254 / circom encoding used by groth16-solana. If your
 *    proofs verify off-chain (snarkjs) but fail on-chain, this ordering is the first suspect.
 *  - vk_ic length must equal nr_pubinputs + 1.
 */
const fs = require("fs");

const to32 = (dec) => {
  let hex = BigInt(dec).toString(16).padStart(64, "0");
  return hex.match(/.{2}/g).map((b) => parseInt(b, 16));
};
const g1 = (p) => [...to32(p[0]), ...to32(p[1])]; // x || y
const g2 = (p) => [
  ...to32(p[0][1]), ...to32(p[0][0]), // x: c1 || c0
  ...to32(p[1][1]), ...to32(p[1][0]), // y: c1 || c0
];
const arr = (bytes) => `[${bytes.join(",")}]`;

function emit(name, vk) {
  const n = vk.nPublic;
  const ic = vk.IC.map((p) => `        ${arr(g1(p))},`).join("\n");
  return `pub const ${name}: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${n},
    vk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
    vk_beta_g2: ${arr(g2(vk.vk_beta_2))},
    vk_gamme_g2: ${arr(g2(vk.vk_gamma_2))},
    vk_delta_g2: ${arr(g2(vk.vk_delta_2))},
    vk_ic: &[
${ic}
    ],
};`;
}

const [, , withdrawPath, ragequitPath, outPath] = process.argv;
const withdraw = JSON.parse(fs.readFileSync(withdrawPath));
const ragequit = JSON.parse(fs.readFileSync(ragequitPath));

const header = `//! AUTO-GENERATED by circuits/scripts/parse_vk_to_rust.js — do not edit by hand.
use groth16_solana::groth16::Groth16Verifyingkey;

`;
fs.writeFileSync(
  outPath,
  header + emit("WITHDRAW_VK", withdraw) + "\n\n" + emit("RAGEQUIT_VK", ragequit) + "\n"
);
console.log(`✅ wrote ${outPath} (withdraw: ${withdraw.nPublic} pub, ragequit: ${ragequit.nPublic} pub)`);
